GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN2YXJzIiwiaWQiOiI1ZmM3N2E3M2JhYTFiMzQyZDAzZWJjNTYiLCJpYXQiOjE2MDY5MzI5MTl9.dMIRtu5P3oKzMpiNMTGHBy0PkPmJovuQ3tgJvhclPyU

{
    "title": "testblog10",
    "author": "nick",
    "url": "blogspot.lul.com",
    "likes": 57
}

### no authorization
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "testblog9",
    "author": "nick",
    "url": "blogspot.lul.com",
    "likes": 57
}

### Capital bearer
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN2YXJzIiwiaWQiOiI1ZmM3N2E3M2JhYTFiMzQyZDAzZWJjNTYiLCJpYXQiOjE2MDY5MzI5MTl9.dMIRtu5P3oKzMpiNMTGHBy0PkPmJovuQ3tgJvhclPyU

{
    "title": "testblog11",
    "author": "nick",
    "url": "blogspot.lul.com",
    "likes": 57
}

### authorization but not bearer
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: seeww eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN2YXJzIiwiaWQiOiI1ZmM3N2E3M2JhYTFiMzQyZDAzZWJjNTYiLCJpYXQiOjE2MDY5MzI5MTl9.dMIRtu5P3oKzMpiNMTGHBy0PkPmJovuQ3tgJvhclPyU

{
    "title": "testblog9",
    "author": "nick",
    "url": "blogspot.lul.com",
    "likes": 57
}
