GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "testblog3",
    "author": "nick3",
    "url": "blogspot3.lul.com",
    "likes": 56
}