GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "testblog4",
    "author": "nick4",
    "url": "blogspot4.lul.com",
    "likes": 57
}