POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "svars",
    "password": "krifoskodikos"
}

### wrong credentials (username)
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "wqwwww",
    "password": "krifoskodikos"
}

### wrong credentials (passwrod)
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "svars",
    "password": "deqd323"
}